### ISSUE TITLE
New liverys not working:737 China eastern and ethopian

### ISSUE THREAD

**Issue by FlamingPitFromGeofs** [Ariakim-Taiyo/LiveryChanger#19]
Hi Ariakim-Taiyo,I could see you have used some new liverys.I love them but there is a problem.The china eastern and Ethiopian are not working.I could see you have fixed the bare metal livery.But my New China eastern and ethipoian doesn't work.Also the air canada doesn't work.I would like to see more A330 choices in the future.I would love a Airbus beluga as well.Thank you

#17 

Flamingpitfromgeofs

**Comment by abinofcake** [comment]
> Hi Ariakim-Taiyo,I could see you have used some new liverys.I love them but there is a problem.The china eastern and Ethiopian are not working.I could see you have fixed the bare metal livery.But my New China eastern and ethipoian doesn't work.Also the air canada doesn't work.I would like to see more A330 choices in the future.I would love a Airbus beluga as well.Thank you
> 
> #17
> 
> Flamingpitfromgeofs

I'm sure you know by know that the China Eastern And Ethiopian liveries are not managed or made by Ariakim Taiyo, this means that you will have to contact the developers who made those liveries. Also, I am pretty sure that this plugin is specifically made for creating liveries, not aircraft.

**Comment by tampermonkey335** [comment]
AFAIK, Ariakim hosts his/her images on his/her own site. That means that every change has to go through him. The problem is prob the image resolutions since Cargolux made it in 3840*3840. It has to be in 4096*4096 or 1024*1024 in order to work. He's been quite inactive these days but you can probably see the problem once you look into the code (or ask him).
